/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    proofOfPayment: ProofOfPayment;
    campApplications: CampApplication;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  roles?: ('admin' | 'user')[] | null;
  phoneNumber: string;
  gender: 'female' | 'male';
  application?: (number | null) | CampApplication;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campApplications".
 */
export interface CampApplication {
  id: number;
  targetGroup: 'child' | '12-25' | '26-35' | '36-45' | '46-55' | '56-65' | '65+';
  nationality:
    | 'Afghanistan'
    | 'Albania'
    | 'Algeria'
    | 'Andorra'
    | 'Angola'
    | 'Antigua and Barbuda'
    | 'Argentina'
    | 'Armenia'
    | 'Australia'
    | 'Austria'
    | 'Azerbaijan'
    | 'Bahamas'
    | 'Bahrain'
    | 'Bangladesh'
    | 'Barbados'
    | 'Belarus'
    | 'Belgium'
    | 'Belize'
    | 'Benin'
    | 'Bhutan'
    | 'Bolivia'
    | 'Bosnia and Herzegovina'
    | 'Botswana'
    | 'Brazil'
    | 'Brunei Darussalam'
    | 'Bulgaria'
    | 'Burkina Faso'
    | 'Burundi'
    | 'Cambodia'
    | 'Cameroon'
    | 'Canada'
    | 'Central African Republic'
    | 'Chad'
    | 'Chile'
    | 'China'
    | 'Colombia'
    | 'Comoros'
    | 'Congo'
    | 'Costa Rica'
    | 'Côte d Ivoire'
    | 'Croatia'
    | 'Cuba'
    | 'Cyprus'
    | 'Czech Republic'
    | 'Denmark'
    | 'Djibouti'
    | 'Dominica'
    | 'Dominican Republic'
    | 'Ecuador'
    | 'Egypt'
    | 'El Salvador'
    | 'Equatorial Guinea'
    | 'Eritrea'
    | 'Estonia'
    | 'Ethiopia'
    | 'Fiji'
    | 'Finland'
    | 'France'
    | 'Gabon'
    | 'Gambia'
    | 'Georgia'
    | 'Germany'
    | 'Ghana'
    | 'Greece'
    | 'Grenada'
    | 'Guatemala'
    | 'Guinea'
    | 'Guinea-Bissau'
    | 'Guyana'
    | 'Haiti'
    | 'Honduras'
    | 'Hungary'
    | 'Iceland'
    | 'India'
    | 'Indonesia'
    | 'Iran'
    | 'Iraq'
    | 'Ireland'
    | 'Israel'
    | 'Italy'
    | 'Jamaica'
    | 'Japan'
    | 'Jordan'
    | 'Kazakhstan'
    | 'Kenya'
    | 'Kiribati'
    | 'North Korea'
    | 'South Korea'
    | 'Kuwait'
    | 'Kyrgyzstan'
    | 'Lao People`s Democratic Republic'
    | 'Latvia'
    | 'Lebanon'
    | 'Lesotho'
    | 'Liberia'
    | 'Libya'
    | 'Liechtenstein'
    | 'Lithuania'
    | 'Luxembourg'
    | 'Macedonia'
    | 'Madagascar'
    | 'Malawi'
    | 'Malaysia'
    | 'Maldives'
    | 'Mali'
    | 'Malta'
    | 'Marshall Islands'
    | 'Mauritania'
    | 'Mauritius'
    | 'Mexico'
    | 'Micronesia'
    | 'Moldova'
    | 'Monaco'
    | 'Mongolia'
    | 'Montenegro'
    | 'Morocco'
    | 'Mozambique'
    | 'Myanmar'
    | 'Namibia'
    | 'Nauru'
    | 'Nepal'
    | 'Netherlands'
    | 'New Zealand'
    | 'Nicaragua'
    | 'Niger'
    | 'Nigeria'
    | 'Norway'
    | 'Oman'
    | 'Pakistan'
    | 'Palau'
    | 'Papua New Guinea'
    | 'Paraguay'
    | 'Peru'
    | 'Philippines'
    | 'Poland'
    | 'Portugal'
    | 'Qatar'
    | 'Romania'
    | 'Russian Federation'
    | 'Rwanda'
    | 'Saint Kitts and Nevis'
    | 'Saint Lucia'
    | 'Saint Vincent and the Grenadines'
    | 'Samoa'
    | 'San Marino'
    | 'Sao Tome and Principe'
    | 'Saudi Arabia'
    | 'Senegal'
    | 'Serbia'
    | 'Seychelles'
    | 'Sierra Leone'
    | 'Singapore'
    | 'Sint Maarten'
    | 'Slovakia'
    | 'Slovenia'
    | 'Solomon Islands'
    | 'Somalia'
    | 'South Africa'
    | 'South Sudan'
    | 'Spain'
    | 'Sri Lanka'
    | 'Sudan'
    | 'Suriname'
    | 'Swaziland'
    | 'Sweden'
    | 'Switzerland'
    | 'Syrian Arab Republic'
    | 'Tajikistan'
    | 'Tanzania'
    | 'Thailand'
    | 'Timor-Leste'
    | 'Togo'
    | 'Tonga'
    | 'Trinidad and Tobago'
    | 'Tunisia'
    | 'Turkey'
    | 'Turkmenistan'
    | 'Tuvalu'
    | 'Uganda'
    | 'Ukraine'
    | 'United Arab Emirates'
    | 'United Kingdom'
    | 'United States'
    | 'Uruguay'
    | 'Uzbekistan'
    | 'Vanuatu'
    | 'Vatican City State'
    | 'Venezuela'
    | 'Viet Nam'
    | 'Yemen'
    | 'Zambia'
    | 'Zimbabwe';
  churchOrganisationName: string;
  churchLocation: string;
  otherDenomination?: string | null;
  howDidYouLearnAboutUs?: ('Referral from others' | 'Social media' | 'Church Announcements') | null;
  expetationsFromConference: string;
  additionalInformation: string;
  arrivalDate: string;
  departureDate: string;
  participatesInSinging: 'Yes' | 'No';
  typeOfGroup?: ('Solo performance' | 'Group performance') | null;
  preferredComunication?: ('WhatsApp' | 'Email') | null;
  proofOfPayment?: (number | null) | ProofOfPayment;
  validAppication?: boolean | null;
  invalidApplicationReason?: string | null;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proofOfPayment".
 */
export interface ProofOfPayment {
  id: number;
  user: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'proofOfPayment';
        value: number | ProofOfPayment;
      } | null)
    | ({
        relationTo: 'campApplications';
        value: number | CampApplication;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}