name: Deploy to Cloud Run

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Create env file
        run: |
          echo ${{ secrets.ENVS }} >> .env
      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Build Docker Image
        run: |
          echo ${{ secrets.ENVS }} > extra_env
          docker build -t ${{ secrets.DOCKER_IMAGE_URL }}:latest --build-arg EXTRA_ENV=$(grep -Ev '^(#|$)' extra_env | xargs) .
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME ${{ secrets.SERVICE_NAME }}
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image ${{ secrets.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated
